services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - DOCKER_API_URL=http://backend:5000

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    # ホスト側の ./server ディレクトリをコンテナ側の /app ディレクトリにマウント(割り当てること)
    volumes:
      - ./server:/app
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=analogie_finder

# 名前付きボリュームは、ユーザが明示的に場所を指定しなくても、Docker が管理する。
volumes:
  mongo-data:
