version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - DOCKER_API_URL=http://backend:5000
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    # ホスト側の ./server ディレクトリをコンテナ側の /app ディレクトリにマウント(割り当てること)
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./data/db_data/initial-data.json:/docker-entrypoint-initdb.d/initial-data.json
    environment:
      - MONGO_INITDB_DATABASE=analogie_finder
    entrypoint: ["sh", "-c", "mongoimport --host mongo --db analogie_finder --collection patents --type json --file /docker-entrypoint-initdb.d/initial-data.json --jsonArray"]

# 名前付きボリュームは、ユーザが明示的に場所を指定しなくても、Docker が管理する。
volumes:
  mongo-data:
