name: patent_find_py3119
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - google-generativeai==0.7.0
  - grpcio-status==1.62.2
  - isodate==0.6.1
  - outcome==1.3.0.post0
  - pymongo==4.6.3
  - pytest==8.1.1
  - setuptools==65.5.0
  - pip
  - pip:
      - flask-cors==4.0.1
      - openai==1.21.1
      - pymupdf==1.24.2